using PhoneNumbers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;

namespace HRMS.Core.Helpers
{
    public class TelephoneNumberHelper
    {
        public static string Format(string PhoneNumberInput, string CountryCode)
        {
            PhoneNumberUtil PNUtil = PhoneNumberUtil.GetInstance();
            PhoneNumbers.PhoneNumber ProcessedNumber = PNUtil.Parse(PhoneNumberInput, CountryCode);

            StringBuilder output = new StringBuilder();

            PNUtil.Format(ProcessedNumber, PhoneNumberFormat.INTERNATIONAL, output);

            return output.ToString();
        } 
        public static string GetCode(string Country)
        {
            try
            {
                return Codes.Where((c) => c.Value.ToLower() == Country.ToLower()).FirstOrDefault().Key;
            }
            catch (Exception e)
            {

                return null;
            }
        }

        public static string GetCountry(string code)
        {
            try
            {
                return Codes.Where((c) => c.Key.ToLower() == code.ToLower()).FirstOrDefault().Value;
            }
            catch (Exception e)
            {
                return null;
            }
        }

        public static List<KeyValuePair<string, string>> GetCodes()
        {
            return Codes;
        }

        public static List<KeyValuePair<string, string>> Codes = new List<KeyValuePair<string, string>> {
             new KeyValuePair<string, string>("AD", "Andorra"),
             new KeyValuePair<string, string>("AE", "United Arab Emirates"),
             new KeyValuePair<string, string>("AF", "Afghanistan"),
             new KeyValuePair<string, string>("AG", "Antigua and Barbuda"),
             new KeyValuePair<string, string>("AI", "Anguilla"),
             new KeyValuePair<string, string>("AL", "Albania"),
             new KeyValuePair<string, string>("AM", "Armenia"),
             new KeyValuePair<string, string>("AO", "Angola"),
             new KeyValuePair<string, string>("AQ", "Antarctica"),
             new KeyValuePair<string, string>("AR", "Argentina"),
             new KeyValuePair<string, string>("AS", "American Samoa"),
             new KeyValuePair<string, string>("AT", "Austria"),
             new KeyValuePair<string, string>("AU", "Australia"),
             new KeyValuePair<string, string>("AW", "Aruba"),
             new KeyValuePair<string, string>("AX", "Åland Islands"),
             new KeyValuePair<string, string>("AZ", "Azerbaijan"),
             new KeyValuePair<string, string>("BA", "Bosnia and Herzegovina"),
             new KeyValuePair<string, string>("BB", "Barbados"),
             new KeyValuePair<string, string>("BD", "Bangladesh"),
             new KeyValuePair<string, string>("BE", "Belgium"),
             new KeyValuePair<string, string>("BF", "Burkina Faso"),
             new KeyValuePair<string, string>("BG", "Bulgaria"),
             new KeyValuePair<string, string>("BH", "Bahrain"),
             new KeyValuePair<string, string>("BI", "Burundi"),
             new KeyValuePair<string, string>("BJ", "Benin"),
             new KeyValuePair<string, string>("BL", "Saint Barthélemy"),
             new KeyValuePair<string, string>("BM", "Bermuda"),
             new KeyValuePair<string, string>("BN", "Brunei Darussalam"),
             new KeyValuePair<string, string>("BO", "Bolivia, Plurinational State of"),
             new KeyValuePair<string, string>("BQ", "Bonaire, Sint Eustatius and Saba"),
             new KeyValuePair<string, string>("BR", "Brazil"),
             new KeyValuePair<string, string>("BS", "Bahamas"),
             new KeyValuePair<string, string>("BT", "Bhutan"),
             new KeyValuePair<string, string>("BV", "Bouvet Island"),
             new KeyValuePair<string, string>("BW", "Botswana"),
             new KeyValuePair<string, string>("BY", "Belarus"),
             new KeyValuePair<string, string>("BZ", "Belize"),
             new KeyValuePair<string, string>("CA", "Canada"),
             new KeyValuePair<string, string>("CC", "Cocos (Keeling) Islands"),
             new KeyValuePair<string, string>("CD", "Congo, the Democratic Republic of the"),
             new KeyValuePair<string, string>("CF", "Central African Republic"),
             new KeyValuePair<string, string>("CG", "Congo"),
             new KeyValuePair<string, string>("CH", "Switzerland"),
             new KeyValuePair<string, string>("CI", "Côte d'Ivoire"),
             new KeyValuePair<string, string>("CK", "Cook Islands"),
             new KeyValuePair<string, string>("CL", "Chile"),
             new KeyValuePair<string, string>("CM", "Cameroon"),
             new KeyValuePair<string, string>("CN", "China"),
             new KeyValuePair<string, string>("CO", "Colombia"),
             new KeyValuePair<string, string>("CR", "Costa Rica"),
             new KeyValuePair<string, string>("CU", "Cuba"),
             new KeyValuePair<string, string>("CV", "Cape Verde"),
             new KeyValuePair<string, string>("CW", "Curaçao"),
             new KeyValuePair<string, string>("CX", "Christmas Island"),
             new KeyValuePair<string, string>("CY", "Cyprus"),
             new KeyValuePair<string, string>("CZ", "Czech Republic"),
             new KeyValuePair<string, string>("DE", "Germany"),
             new KeyValuePair<string, string>("DJ", "Djibouti"),
             new KeyValuePair<string, string>("DK", "Denmark"),
             new KeyValuePair<string, string>("DM", "Dominica"),
             new KeyValuePair<string, string>("DO", "Dominican Republic"),
             new KeyValuePair<string, string>("DZ", "Algeria"),
             new KeyValuePair<string, string>("EC", "Ecuador"),
             new KeyValuePair<string, string>("EE", "Estonia"),
             new KeyValuePair<string, string>("EG", "Egypt"),
             new KeyValuePair<string, string>("EH", "Western Sahara"),
             new KeyValuePair<string, string>("ER", "Eritrea"),
             new KeyValuePair<string, string>("ES", "Spain"),
             new KeyValuePair<string, string>("ET", "Ethiopia"),
             new KeyValuePair<string, string>("FI", "Finland"),
             new KeyValuePair<string, string>("FJ", "Fiji"),
             new KeyValuePair<string, string>("FK", "Falkland Islands (Malvinas)"),
             new KeyValuePair<string, string>("FM", "Micronesia, Federated States of"),
             new KeyValuePair<string, string>("FO", "Faroe Islands"),
             new KeyValuePair<string, string>("FR", "France"),
             new KeyValuePair<string, string>("GA", "Gabon"),
             new KeyValuePair<string, string>("GB", "United Kingdom"),
             new KeyValuePair<string, string>("GD", "Grenada"),
             new KeyValuePair<string, string>("GE", "Georgia"),
             new KeyValuePair<string, string>("GF", "French Guiana"),
             new KeyValuePair<string, string>("GG", "Guernsey"),
             new KeyValuePair<string, string>("GH", "Ghana"),
             new KeyValuePair<string, string>("GI", "Gibraltar"),
             new KeyValuePair<string, string>("GL", "Greenland"),
             new KeyValuePair<string, string>("GM", "Gambia"),
             new KeyValuePair<string, string>("GN", "Guinea"),
             new KeyValuePair<string, string>("GP", "Guadeloupe"),
             new KeyValuePair<string, string>("GQ", "Equatorial Guinea"),
             new KeyValuePair<string, string>("GR", "Greece"),
             new KeyValuePair<string, string>("GS", "South Georgia and the South Sandwich Islands"),
             new KeyValuePair<string, string>("GT", "Guatemala"),
             new KeyValuePair<string, string>("GU", "Guam"),
             new KeyValuePair<string, string>("GW", "Guinea-Bissau"),
             new KeyValuePair<string, string>("GY", "Guyana"),
             new KeyValuePair<string, string>("HK", "Hong Kong"),
             new KeyValuePair<string, string>("HM", "Heard Island and McDonald Islands"),
             new KeyValuePair<string, string>("HN", "Honduras"),
             new KeyValuePair<string, string>("HR", "Croatia"),
             new KeyValuePair<string, string>("HT", "Haiti"),
             new KeyValuePair<string, string>("HU", "Hungary"),
             new KeyValuePair<string, string>("ID", "Indonesia"),
             new KeyValuePair<string, string>("IE", "Ireland"),
             new KeyValuePair<string, string>("IL", "Israel"),
             new KeyValuePair<string, string>("IM", "Isle of Man"),
             new KeyValuePair<string, string>("IN", "India"),
             new KeyValuePair<string, string>("IO", "British Indian Ocean Territory"),
             new KeyValuePair<string, string>("IQ", "Iraq"),
             new KeyValuePair<string, string>("IR", "Iran, Islamic Republic of"),
             new KeyValuePair<string, string>("IS", "Iceland"),
             new KeyValuePair<string, string>("IT", "Italy"),
             new KeyValuePair<string, string>("JE", "Jersey"),
             new KeyValuePair<string, string>("JM", "Jamaica"),
             new KeyValuePair<string, string>("JO", "Jordan"),
             new KeyValuePair<string, string>("JP", "Japan"),
             new KeyValuePair<string, string>("KE", "Kenya"),
             new KeyValuePair<string, string>("KG", "Kyrgyzstan"),
             new KeyValuePair<string, string>("KH", "Cambodia"),
             new KeyValuePair<string, string>("KI", "Kiribati"),
             new KeyValuePair<string, string>("KM", "Comoros"),
             new KeyValuePair<string, string>("KN", "Saint Kitts and Nevis"),
             new KeyValuePair<string, string>("KP", "Korea, Democratic People's Republic of"),
             new KeyValuePair<string, string>("KR", "Korea, Republic of"),
             new KeyValuePair<string, string>("KW", "Kuwait"),
             new KeyValuePair<string, string>("KY", "Cayman Islands"),
             new KeyValuePair<string, string>("KZ", "Kazakhstan"),
             new KeyValuePair<string, string>("LA", "Lao People's Democratic Republic"),
             new KeyValuePair<string, string>("LB", "Lebanon"),
             new KeyValuePair<string, string>("LC", "Saint Lucia"),
             new KeyValuePair<string, string>("LI", "Liechtenstein"),
             new KeyValuePair<string, string>("LK", "Sri Lanka"),
             new KeyValuePair<string, string>("LR", "Liberia"),
             new KeyValuePair<string, string>("LS", "Lesotho"),
             new KeyValuePair<string, string>("LT", "Lithuania"),
             new KeyValuePair<string, string>("LU", "Luxembourg"),
             new KeyValuePair<string, string>("LV", "Latvia"),
             new KeyValuePair<string, string>("LY", "Libya"),
             new KeyValuePair<string, string>("MA", "Morocco"),
             new KeyValuePair<string, string>("MC", "Monaco"),
             new KeyValuePair<string, string>("MD", "Moldova, Republic of"),
             new KeyValuePair<string, string>("ME", "Montenegro"),
             new KeyValuePair<string, string>("MF", "Saint Martin (French part)"),
             new KeyValuePair<string, string>("MG", "Madagascar"),
             new KeyValuePair<string, string>("MH", "Marshall Islands"),
             new KeyValuePair<string, string>("MK", "Macedonia"),
             new KeyValuePair<string, string>("ML", "Mali"),
             new KeyValuePair<string, string>("MM", "Myanmar"),
             new KeyValuePair<string, string>("MN", "Mongolia"),
             new KeyValuePair<string, string>("MO", "Macao"),
             new KeyValuePair<string, string>("MP", "Northern Mariana Islands"),
             new KeyValuePair<string, string>("MQ", "Martinique"),
             new KeyValuePair<string, string>("MR", "Mauritania"),
             new KeyValuePair<string, string>("MS", "Montserrat"),
             new KeyValuePair<string, string>("MT", "Malta"),
             new KeyValuePair<string, string>("MU", "Mauritius"),
             new KeyValuePair<string, string>("MV", "Maldives"),
             new KeyValuePair<string, string>("MW", "Malawi"),
             new KeyValuePair<string, string>("MX", "Mexico"),
             new KeyValuePair<string, string>("MY", "Malaysia"),
             new KeyValuePair<string, string>("MZ", "Mozambique"),
             new KeyValuePair<string, string>("NA", "Namibia"),
             new KeyValuePair<string, string>("NC", "New Caledonia"),
             new KeyValuePair<string, string>("NE", "Niger"),
             new KeyValuePair<string, string>("NF", "Norfolk Island"),
             new KeyValuePair<string, string>("NG", "Nigeria"),
             new KeyValuePair<string, string>("NI", "Nicaragua"),
             new KeyValuePair<string, string>("NL", "Netherlands"),
             new KeyValuePair<string, string>("NO", "Norway"),
             new KeyValuePair<string, string>("NP", "Nepal"),
             new KeyValuePair<string, string>("NR", "Nauru"),
             new KeyValuePair<string, string>("NU", "Niue"),
             new KeyValuePair<string, string>("NZ", "New Zealand"),
             new KeyValuePair<string, string>("OM", "Oman"),
             new KeyValuePair<string, string>("PA", "Panama"),
             new KeyValuePair<string, string>("PE", "Peru"),
             new KeyValuePair<string, string>("PF", "French Polynesia"),
             new KeyValuePair<string, string>("PG", "Papua New Guinea"),
             new KeyValuePair<string, string>("PH", "Philippines"),
             new KeyValuePair<string, string>("PK", "Pakistan"),
             new KeyValuePair<string, string>("PL", "Poland"),
             new KeyValuePair<string, string>("PM", "Saint Pierre and Miquelon"),
             new KeyValuePair<string, string>("PN", "Pitcairn"),
             new KeyValuePair<string, string>("PR", "Puerto Rico"),
             new KeyValuePair<string, string>("PS", "Palestine, State of"),
             new KeyValuePair<string, string>("PT", "Portugal"),
             new KeyValuePair<string, string>("PW", "Palau"),
             new KeyValuePair<string, string>("PY", "Paraguay"),
             new KeyValuePair<string, string>("QA", "Qatar"),
             new KeyValuePair<string, string>("RE", "Réunion"),
             new KeyValuePair<string, string>("RO", "Romania"),
             new KeyValuePair<string, string>("RS", "Serbia"),
             new KeyValuePair<string, string>("RU", "Russian Federation"),
             new KeyValuePair<string, string>("RW", "Rwanda"),
             new KeyValuePair<string, string>("SA", "Saudi Arabia"),
             new KeyValuePair<string, string>("SB", "Solomon Islands"),
             new KeyValuePair<string, string>("SC", "Seychelles"),
             new KeyValuePair<string, string>("SD", "Sudan"),
             new KeyValuePair<string, string>("SE", "Sweden"),
             new KeyValuePair<string, string>("SG", "Singapore"),
             new KeyValuePair<string, string>("SH", "Saint Helena, Ascension and Tristan da Cunha"),
             new KeyValuePair<string, string>("SI", "Slovenia"),
             new KeyValuePair<string, string>("SJ", "Svalbard and Jan Mayen"),
             new KeyValuePair<string, string>("SK", "Slovakia"),
             new KeyValuePair<string, string>("SL", "Sierra Leone"),
             new KeyValuePair<string, string>("SM", "San Marino"),
             new KeyValuePair<string, string>("SN", "Senegal"),
             new KeyValuePair<string, string>("SO", "Somalia"),
             new KeyValuePair<string, string>("SR", "Suriname"),
             new KeyValuePair<string, string>("SS", "South Sudan"),
             new KeyValuePair<string, string>("ST", "Sao Tome and Principe"),
             new KeyValuePair<string, string>("SV", "El Salvador"),
             new KeyValuePair<string, string>("SX", "Sint Maarten (Dutch part)"),
             new KeyValuePair<string, string>("SY", "Syrian Arab Republic"),
             new KeyValuePair<string, string>("SZ", "Swaziland"),
             new KeyValuePair<string, string>("TC", "Turks and Caicos Islands"),
             new KeyValuePair<string, string>("TD", "Chad"),
             new KeyValuePair<string, string>("TF", "French Southern Territories"),
             new KeyValuePair<string, string>("TG", "Togo"),
             new KeyValuePair<string, string>("TH", "Thailand"),
             new KeyValuePair<string, string>("TJ", "Tajikistan"),
             new KeyValuePair<string, string>("TK", "Tokelau"),
             new KeyValuePair<string, string>("TL", "Timor-Leste"),
             new KeyValuePair<string, string>("TM", "Turkmenistan"),
             new KeyValuePair<string, string>("TN", "Tunisia"),
             new KeyValuePair<string, string>("TO", "Tonga"),
             new KeyValuePair<string, string>("TR", "Turkey"),
             new KeyValuePair<string, string>("TT", "Trinidad and Tobago"),
             new KeyValuePair<string, string>("TV", "Tuvalu"),
             new KeyValuePair<string, string>("TW", "Taiwan, Province of China"),
             new KeyValuePair<string, string>("TZ", "Tanzania, United Republic of"),
             new KeyValuePair<string, string>("UA", "Ukraine"),
             new KeyValuePair<string, string>("UG", "Uganda"),
             new KeyValuePair<string, string>("UM", "United States Minor Outlying Islands"),
             new KeyValuePair<string, string>("US", "United States"),
             new KeyValuePair<string, string>("UY", "Uruguay"),
             new KeyValuePair<string, string>("UZ", "Uzbekistan"),
             new KeyValuePair<string, string>("VA", "Holy See (Vatican City State)"),
             new KeyValuePair<string, string>("VC", "Saint Vincent and the Grenadines"),
             new KeyValuePair<string, string>("VE", "Venezuela, Bolivarian Republic of"),
             new KeyValuePair<string, string>("VG", "Virgin Islands, British"),
             new KeyValuePair<string, string>("VI", "Virgin Islands, U.S."),
             new KeyValuePair<string, string>("VN", "Viet Nam"),
             new KeyValuePair<string, string>("VU", "Vanuatu"),
             new KeyValuePair<string, string>("WF", "Wallis and Futuna"),
             new KeyValuePair<string, string>("WS", "Samoa"),
             new KeyValuePair<string, string>("YE", "Yemen"),
             new KeyValuePair<string, string>("YT", "Mayotte"),
             new KeyValuePair<string, string>("ZA", "South Africa"),
             new KeyValuePair<string, string>("ZM", "Zambia"),
             new KeyValuePair<string, string>("ZW", "Zimbabwe"),
        };
    }
}